services:
  app:
    build: .
    working_dir: /app
    ports:
      - '3000:3000'
      - '24678:24678'
    environment:
      - NUXT_ADMIN_PASSWORD=${NUXT_ADMIN_PASSWORD}
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
    volumes:
      - .:/app
    tty: true
